<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('header');

?>
    <div style="background-image: url('<?=Asset::image('background.png')?>');width: 100%;height: 200px;background-repeat: repeat-x;background-size: contain;background-position: center;">
        </br>
        </br>
        <h1 style="color: white;">Gestão de contas</h1>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome Real</th>
            <th>Username</th>
            <th>Email</th>
            <th>Data de nascimento</th>
            <th>Tipo de utilizador</th>
            <th>Ação</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach (User::all() as $user) { ?>
            <tr>
                <td><?= $user->idutilizador ?></td>
                <td><?= $user->nomecompleto ?></td>
                <td><?= $user->username ?></td>
                <td><?= $user->email ?></td>
                <td><?= $user->datanasc->format('d-m-Y') ?></td>
                <td><?= $user->nivelacesso == 2 ? 'Administrador' : 'Jogador' ?></td>
                <?php if ($user->bloqueado == 0) { ?>
                    <td><a href="<?= URL::toRoute('users/bloquear', $user->idutilizador) ?>" class="btn btn-danger">Bloquear</a>
                    </td>
                <?php } else { ?>
                    <td><a href="<?= URL::toRoute('users/bloquear', $user->idutilizador) ?>" class="btn btn-primary">Desbloquear</a>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
        </tbody>
    </table>

<?php Layout::includeLayout('footer'); ?>