<!doctype html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1><a>Iniciar Jogo</a></h1>

<div style="border: double; width: 26%">
    <button class="b_numero" style="margin-right: 30px"> 1 </button>
    <button class="b_numero" style="margin-right: 30px"> 2 </button>
    <button class="b_numero" style="margin-right: 30px"> 3 </button>
    <button class="b_numero" style="margin-right: 30px"> 4 </button>
    <button class="b_numero" style="margin-right: 30px"> 5 </button>
    <button class="b_numero" style="margin-right: 30px"> 6 </button>
    <button class="b_numero" style="margin-right: 30px"> 7 </button>
    <button class="b_numero" style="margin-right: 30px"> 8 </button>
    <button class="b_numero"> 9 </button>
</div>
    <table border="2"width="100%" height="400px">

    </table>
<div style="border: double; width: 26%">
    <button class="b_numero2" style="margin-right: 30px"> 1 </button>
    <button class="b_numero2" style="margin-right: 30px"> 2 </button>
    <button class="b_numero2" style="margin-right: 30px"> 3 </button>
    <button class="b_numero2" style="margin-right: 30px"> 4 </button>
    <button class="b_numero2" style="margin-right: 30px"> 5 </button>
    <button class="b_numero2" style="margin-right: 30px" > 6 </button>
    <button class="b_numero2" style="margin-right: 30px" > 7 </button>
    <button class="b_numero2" style="margin-right: 30px"> 8 </button>
    <button class="b_numero2" > 9 </button>
</div>

</body>
</html>