<?php use ArmoredCore\WebObjects\URL;

\ArmoredCore\WebObjects\Layout::includeLayout('header');
?>
<div>
    <h3 style="color: gray">
        Sign In
    </h3>
</div>
<div style="margin auto; width: 100%; text-align: center; border: groove; display:inline-block">
    <h4 style="font-family: 'Arial Rounded MT Bold'; font-size: 26px">
        Realize login para a sua conta
    </h4>
    <h5 style="font-family: Bahnschrift; font-size: 20px">
        Username: *
        <input id="login" type="text" style="width: 400px">
    </h5>
    <h5 style="font-family: Bahnschrift; font-size: 20px">
        Password: *
        <input id="password" type="text" style="width: 400px">
    </h5>
    <div>
        <h4>

            <button class="btn btn-default" href="#"
                    style="font-family: 'Arial MT'; font-size: 18px; display:inline-block">
                Registrar
            </button>

            <button class="btn btn-default" href="#"
                    style="font-family: 'Arial MT'; font-size: 18px; display:inline-block">
                Sign In
            </button>


        </h4>
    </div>
</div>


</body>
</html>

