<?php use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header');
?>
<div style="">
    <div class="row">
        <article class="col-xs-12 maincontent">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="thin text-center">Login</h3>
                        <p class="text-center text-muted">Antes de poder jogar, tem que fazer login.</p>
                        <hr>

                        <form method="post" action="<?= URL::toRoute('users/login') ?>">
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="username" required>
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="password" required>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-lg-8">
                                    <a href="<?= URL::toRoute('jogo/registo') ?>">Registar</a>
                                </div>
                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Login</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>

<?php Layout::includeLayout('footer'); ?>
