<?php use ArmoredCore\WebObjects\URL;

\ArmoredCore\WebObjects\Layout::includeLayout('header');
?>
<div>
    <h3 style="color: gray">
        Sign In
    </h3>
</div>
<div style="margin auto; width: 100%; text-align: center; border: groove;">
    <h4 style="font-family: 'Arial Rounded MT Bold'; font-size: 26px">
        Realize login para a sua conta
    </h4>
    <h5 style="font-family: Bahnschrift; font-size: 20px">
        Username: *
        <input id="login" type="text" style="width: 400px">
    </h5>
    <h5 style="font-family: Bahnschrift; font-size: 20px">
        Password: *
        <input id="password" type="text" style="width: 400px">
    </h5>
    <h4>
        <a href="#" style="font-family: 'Arial Rounded MT Bold'; font-size: 24px; align:left" >Registrar</a>
        <button href="#" style="font-family: 'Arial Rounded MT Bold'; font-size: 24px; align:right">Sign In </button>
    </h4>
</div>


</body>
</html>

