<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header');
$melhorespontuacoes = Data::get('mp');
$i = 0;
?>
    <h1 style="font-family: 'Bauhaus 93'">
        Top 10
    </h1>
    <div class="panel panel-success">
        <div class="panel-heading">
            <?php foreach ($melhorespontuacoes as $pontuacao) {
                $i += 1;
                $user = User::find($pontuacao->idutilizador);
           ?>
            <h3>
                <?=$i?> | <?=$user->username ?> | <?= $pontuacao->score?>
            </h3>
            <?php
            }?>
        </div>

    </div>

<?php Layout::includeLayout('footer'); ?>