<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header');
$melhorespontuacoes = Data::get('mp');
$i = 0;
?>


    <div>
        <h1 class="textoCentrado">Top 10</h1>
        <div class="alert alert-info alertScores">Aqui poderá verificar a posição global dos scores, comparando quais os utilizadores que estão em primeiro lugar.</div>

        <table class="table tabelaScores">
            <thead>
            <tr>
                <th class="textoCentrado">Posição</th>
                <th class="textoCentrado">Jogador</th>
                <th class="textoCentrado">Pontos</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($melhorespontuacoes as $pontuacao) {
                $i += 1;
                $user = User::find($pontuacao->idutilizador); ?>
                <tr class="success">
                    <td><?= $i ?></td>
                    <td><a href="<?= URL::toRoute('jogo/perfil', $user->idutilizador) ?>"><?= $user->username ?></a></td>
                    <td><?= $pontuacao->score ?></td>
                </tr>
            <?php }?>
            </tbody>
        </table>
    </div>

<?php Layout::includeLayout('footer'); ?>