<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header');
$melhorespontuacoes = Data::get('mp');
$i = 0;
?>
    <div style="font-size: 17px; font-family: Arial">
        <p>Aqui poderá verificar a posição global dos scores, comparando quais os utilizadores que estão em primeiro lugar.</p>
    </div>
    <h1 style="font-family: 'Bauhaus 93'">
        Top 10
    </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Posição</th>
                <th>Jogador</th>
                <th>Pontos</th>
                <th>Data/hora</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($melhorespontuacoes as $pontuacao) {
                $i += 1;
                $user = User::find($pontuacao->idutilizador); ?>
                <tr class="success">
                    <td><?= $i ?></td>
                    <td><?= $user->username ?></td>
                    <td><?= $pontuacao->score ?></td>
                    <td><?= $pontuacao->datahora->format('d-m-Y H:i') ?></td>
                </tr>
                <?php
            }?>
        </tbody>
    </table>
        </br>

<?php Layout::includeLayout('footer'); ?>