<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
?>
<div style="">
    <div class="row">
        <article class="col-xs-12 maincontent">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="thin text-center">Registo</h3>
                        <p class="text-center text-muted">Realize o registo antes de começar a jogar.</p>
                        <hr>

                        <form method="post" action="<?= URL::toRoute('users/registo') ?>">
                            <div class="row">
                                <div class="top-margin col-lg-6">
                                    <label>Nome <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" name="nome" required>
                                </div>

                                <div class="top-margin col-lg-6">
                                    <label>Apelido <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" name="apelido" required>
                                </div>
                            </div>

                            <div class="top-margin">
                                <label>Data de nascimento <span class="text-danger">*</span></label>
                                <input type="date" class="form-control" name="datanasc" required>
                            </div>

                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="username" required>
                            </div>

                            <div class="top-margin">
                                <label>Email <span class="text-danger">*</span></label>
                                <input type="email" class="form-control" name="email" required>
                            </div>

                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="password" required>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-lg-1 text-center">
                                    <button class="btn btn-primary" type="submit">Registar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
<?php Layout::includeLayout('footer'); ?>