<?php use ArmoredCore\WebObjects\URL;

\ArmoredCore\WebObjects\Layout::includeLayout('header');
?>
<div style="">
    <div class="row">
        <article class="col-xs-12 maincontent">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="thin text-center">Registo</h3>
                        <p class="text-center text-muted">Realize o registo antes de começar a jogar.</p>
                        <hr>

                        <form>
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Email <span class="text-danger">*</span></label>
                                <input type="email" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Nivel <span class="text-danger">*</span></label>
                                <input type="nivel" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Nome <span class="text-danger">*</span></label>
                                <input type="nome" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Apelido <span class="text-danger">*</span></label>
                                <input type="apelido" class="form-control">
                            </div>


                            <hr>

                            <div class="row">

                                <div class="col-lg-1 text-right">
                                    <button class="btn btn-action" type="submit">Registar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
</body>
</html>

