<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header');
$engine = Data::get('ge');

if ($engine->getEstadoJogo() == 1) { ?>
    <a href="<?= URL::toRoute('jogo/rolardados') ?>">Rolar dados</a>
<?php } else if ($engine->getEstadoJogo() == 2) {
    echo $engine->tabuleiro->resultadoDado1 . ' + ' . $engine->tabuleiro->resultadoDado2;
    ?>

<?php
}
?>

<div class="centro">
    <div class="tabuleiro">
        <div class="botoes">
            <?php
                for($i = 1; $i <= 9; $i++) { ?>
                    <button class="btn btn-default botaoTabuleiro"><?= $i ?></button>
            <?php
                }
            ?>
        </div>

        <div class="meioTabuleiro">
            <div style="display: inline-block; margin-right: 30%">
                <p>Jogador 1:</p>
                <p>0</p>
            </div>
            <div style="display: inline-block">
                <p>Jogador 2:</p>
                <p>0</p>
            </div>
        </div>

        <div class="botoes">
            <?php
                for($i = 1; $i <= 9; $i++) { ?>
                    <button class="btn btn-default botaoTabuleiro"><?= $i ?></button>
            <?php
                }
            ?>
        </div>
    </div>

    <div class="dados">
        <?php if($engine->getEstadoJogo() == 1) { ?>
            <a href="<?= URL::toRoute('jogo/rolardados') ?>" class="btn btn-primary">Rolar dados</a>
        <?php } else if($engine->getEstadoJogo() == 2) { ?>
            <img src="<?= Asset::image($engine->tabuleiro->resultadoDado1 . '.png')?>">
            <img src="<?= Asset::image($engine->tabuleiro->resultadoDado2 . '.png')?>">
            <p>À espera da jogada...</p>
        <?php } ?>
    </div>
</div>

</body>
</html>