<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
?>
<!doctype html>
<html lang="pt">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shut the box</title>
    <?=AssetBundler::css()?>
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap.css')?>" media="screen" >
    <link rel="stylesheet" href="<?= Asset::css('/jogo.css') ?>">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

            </button>
            <a class="navbar-brand" href="<?= URL::toRoute('jogo/index') ?>">Shut the box</a>
        </div>

        <ul class="nav navbar-nav navbar-left">
            <li><a href="<?= URL::toRoute('jogo/index') ?>">Home</a></li>
            <li><a href="<?= URL::toRoute('jogo/scoreboard') ?>">Pontuações Top 10</a></li>
            <?php if (Session::has('user')) {
                    $user = Session::get('user');
                    if ($user->nivelacesso == 2)
                    { ?>
                <li><a href="<?= URL::toRoute('jogo/gestao') ?>">Gestão das contas</a></li>
                <?php } } ?>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <?php if(Session::has('user')) { $user = Session::get('user'); ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"><?= $user->username ?>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="<?= URL::toRoute('jogo/perfil', $user->idutilizador) ?>">Ver Perfil</a></li>
                    <li><a href="<?= URL::toRoute('jogo/alteracoesperfil') ?>">Alterar credenciais</a></li>
                    <li><a href="<?= URL::toRoute('users/logout') ?>">Logout</a></li>
                </ul>
            </li>
            <?php } else { ?>
            <li><a href="<?= URL::toRoute('jogo/login') ?>">Login</a></li>
            <?php } ?>
        </ul>
    </div>
</nav>
