<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;?>
<!doctype html>
<html lang="pt">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <?=AssetBundler::css()?>
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

            </button>
            <a class="navbar-brand" href="#">Shut the box</a>
        </div>

        <ul class="nav navbar-nav navbar-left">
            <li><a href="<?= URL::toRoute('jogo/index') ?>">Home</a></li>
            <li><a href="<?= URL::toRoute('jogo/scoreboard') ?>">Pontuações Top 10</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="<?= URL::toRoute('jogo/login') ?>"">Login</a></li>
            </li>
        </ul>
    </div>
</nav>
